global:
  scrape_interval: '10s'

scrape_configs:
  - job_name: "prom-vmselect-self-check"
    static_configs:
      - targets: ['vmselect:8481']
        labels:
          group: 'selfcheck'

  - job_name: "prom-vmalert-self-check"
    static_configs:
      - targets: ['vmalert:8880']
        labels:
          group: 'selfcheck'

  - job_name: "prom-vminsert-self-check"
    static_configs:
      - targets: ['vminsert:8480']
        labels:
          group: 'selfcheck'

  - job_name: "prom-vmagent-self-check"
    static_configs:
      - targets: ['vmagent:8429']
        labels:
          group: 'selfcheck'

  - job_name: "prom-vmauth-self-check"
    static_configs:
      - targets: ['vmauth:8427']
        labels:
          group: 'selfcheck'

  - job_name: "prom-sample-metrics"
    static_configs:
      - targets: ['sample-metrics:8000']
        labels:
          group: 'selfcheck'


  # node exporter to read sys stats from host machine
  - job_name: "prom-node-exporter"
    # path to metrics
    metrics_path: '/metrics'
    static_configs:
      # the host.docker.internal refers to host machine.
      - targets: ['host.docker.internal:9100']
        labels:
          group: 'sys-stats-group'

remote_write:
  - url: http://vmauth:8427
    # basic_auth: 
    #   username: "achingupta"
    #   password: "password"
    # oauth2:
    #   client_id: 0oa7n11raywuhVNpp5d7
    #   client_secret: rx0BZVTpNBose1gOUL30hJbyQe28FvaZ14Z86OXB
    #   scopes:
    #     - 'customScope'
    #   token_url: https://dev-56497839.okta.com/oauth2/default/v1/token
    #   endpoint_params: 
    #     grant_type: 'client_credentials'
    authorization:
      type: "Bearer"
      credentials: "eyJraWQiOiJjU3Rab3dCYVlJMWkwTm9MVnV5WmhydDZXdm13N3hwcVFuSXNVSWwxR21FIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmhaVFZHYmd5SmlFQnlkbXdRZ25YNmFVaXJGeWhldFBSQnZ6YmRsdHJWWGMiLCJpc3MiOiJodHRwczovL2Rldi01NjQ5NzgzOS5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NzEwNjM0NDQsImV4cCI6MTY3MTA2NzA0NCwiY2lkIjoiMG9hN24xMXJheXd1aFZOcHA1ZDciLCJzY3AiOlsiY3VzdG9tU2NvcGUiXSwic3ViIjoiMG9hN24xMXJheXd1aFZOcHA1ZDcifQ.FjdOZQBFuH8ekTHy5JHyz0yC2zzFTh9quLQ6U9kVXGd3nEahMknIKSM-Tzw7yPMmtXtzS7XHmul_TJdDxirtiyefDhyMxyk_uSLTNEgpxa2yqXCPWsfE6f4GCRy1_KIGnm-SsucZe64Nn1POZwbOfIWb8OMVre26gPThQybzfqHVVyz49zSb5-9OsJprkSkqrq5Vkm_V5PVQ3jGM0AGoGa7mftlkgTl2UPwst89-jLIfpGU7_jSiPGXwl8-BAN6WHavk1eLDfT_1VFcUOi3_BOXfRrfj4a8DozkBoWHClxdDQpBo8hBMS2cJLJehsfuW1QEIE3FmvzRltOZkiBeFPg"
