# This is a minimal working definition for prometheus alert manager
global: {}
route: 
  receiver: "junk-receiver"
  routes: []
receivers: [{"name": "junk-receiver"}]

# sample for alert config

# global:
#   # Also possible to place this URL in a file.
#   # Ex: `slack_api_url_file: '/etc/alertmanager/slack_url'`
#   slack_api_url: '<slack_webhook_url>'

# route:
#   receiver: 'slack-notifications'
#   group_by: [alertname, datacenter, app]

# receivers:
# - name: 'slack-notifications'
#   slack_configs:
#   - channel: '#alerts'
#     text: 'https://internal.myorg.net/wiki/alerts/{{ .GroupLabels.app }}/{{ .GroupLabels.alertname }}'
